image: archlinux
packages:
  - nodejs
  - leiningen
  - rsync
sources:
  - https://git.sr.ht/~bbuccianti/fp
environment:
  deploy: deploy@buccianti.dev
secrets:
  - ffb1b60b-9c71-498c-9ba5-b8108512c1b8
tasks:
  - run-tests: |
      cd fp
      lein kaocha --no-watch
  - build: |
      cd fp
      lein do clean, cljsbuild once min
  - deploy: |
      cd fp
      sshopts="-o StrictHostKeyChecking=no -p 12345 -i ~/.ssh/id_rsa"
      rsync -e "ssh $sshopts" -rP resources/ ${deploy}:fp.buccianti.dev/
      ssh $sshopts ${deploy} '~/deploy.sh fp.buccianti.dev'
