image: alpine/edge
packages:
  - lua5.3
  - netcat-openbsd
  - curl
  - nodejs
  - npm
  - rsync
  - openjdk11-jre-headless
sources:
  - https://git.sr.ht/~bbuccianti/fp
environment:
  deploy: deploy@69.164.203.126
secrets:
  - 897094d7-7887-48dd-ad0e-cc2486c76c25
tasks:
  - envsetup: |
      cat .cloudflare >> .buildenv
  - setup: |
      cd fp
      curl -o lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
      chmod +x lein
  - run-tests: |
      cd fp
      npm i ws
      ./lein kaocha --no-watch || lua5.3 notify.lua
  - build: |
      cd fp
      ./lein do clean, cljsbuild once min || lua5.3 notify.lua
  - deploy: |
      cd fp
      npx wrangler pages deploy resources/public --project-name=fp
      lua5.3 notify.lua "$?"
