image: archlinux
packages:
  - curl
  - nodejs
  - npm
  - rsync
  - jre10-openjdk-headless
sources:
  - https://git.sr.ht/~bbuccianti/fp
environment:
  deploy: deploy@buccianti.dev
secrets:
  - ffb1b60b-9c71-498c-9ba5-b8108512c1b8
tasks:
  - setup: |
      cd fp
      curl -o lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
      chmod +x lein
  - run-tests: |
      cd fp
      npm i ws
      ./lein kaocha --no-watch
  - build: |
      cd fp
      ./lein do clean, cljsbuild once min
  - deploy: |
      cd fp
      sshopts="-o StrictHostKeyChecking=no -p 12345"
      rsync -e "ssh $sshopts" -rP resources/ ${deploy}:fp.buccianti.dev/
      ssh $sshopts ${deploy} '~/deploy.sh fp.buccianti.dev'
